version: '3.1'
services:
  wordpress:
    build: ./docker
    ports:
    - 8000:8000
    depends_on:
    - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: database
      WORDPRESS_URL: http://localhost:8000
    volumes:
    - ./theme:/wordpress/wp-content/themes/ipcasacaiada
    - uploads:/wordpress/wp-content/uploads:rw
    - plugins:/wordpress/wp-content/plugins:rw

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: rootpassword
    volumes:
    - database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
    - 8001:80
    depends_on:
    - db

volumes:
  database:
  uploads:
  plugins:
